services:
  backend:
    build: ./Server
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - talkforum_default

  frontend:
    build: ./client
    restart: unless-stopped
    networks:
      - talkforum_default

networks:
  talkforum_default:
    external: true
